#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCEDCO.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NCEDCO")]
	public partial class DBLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBLinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NCEDCOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISgetSequence")]
		public ISingleResult<DCISgetSequenceResult> DCISgetSequence([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SequenceName", DbType="VarChar(50)")] string sequenceName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sequenceName);
			return ((ISingleResult<DCISgetSequenceResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISsetParentCustomerRequest")]
		public int DCISsetParentCustomerRequest(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestId", DbType="VarChar(20)")] string requestId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telephone", DbType="VarChar(20)")] string telephone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="VarChar(20)")] string fax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(1)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(50)")] string address1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="NVarChar(50)")] string address2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address3", DbType="NVarChar(50)")] string address3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="VarChar(20)")] string createdBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string isSVat, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserId", DbType="VarChar(20)")] string adminUserId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminPassword", DbType="VarChar(200)")] string adminPassword, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonName", DbType="VarChar(150)")] string contactPersonName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonDesignation", DbType="VarChar(50)")] string contactPersonDesignation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonDirectPhoneNumber", DbType="VarChar(20)")] string contactPersonDirectPhoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonMobile", DbType="VarChar(20)")] string contactPersonMobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonEmail", DbType="VarChar(50)")] string contactPersonEmail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NCEMember", DbType="VarChar(10)")] string nCEMember, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminName", DbType="VarChar(150)")] string adminName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestId, name, telephone, email, fax, status, address1, address2, address3, createdBy, isSVat, adminUserId, adminPassword, contactPersonName, contactPersonDesignation, contactPersonDirectPhoneNumber, contactPersonMobile, contactPersonEmail, nCEMember, adminName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISgetParentCustomerRequestList")]
		public ISingleResult<DCISgetParentCustomerRequestListResult> DCISgetParentCustomerRequestList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(5)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), status);
			return ((ISingleResult<DCISgetParentCustomerRequestListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISgetParentCustomerRequestDetails")]
		public ISingleResult<DCISgetParentCustomerRequestDetailsResult> DCISgetParentCustomerRequestDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestID", DbType="VarChar(20)")] string requestID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestID);
			return ((ISingleResult<DCISgetParentCustomerRequestDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISsetUpdateParentCustomerReq")]
		public int DCISsetUpdateParentCustomerReq([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(1)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestID", DbType="VarChar(20)")] string requestID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), status, requestID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISsetApproveParentCustomer")]
		public int DCISsetApproveParentCustomer(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestId", DbType="VarChar(20)")] string requestId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentCustomerID", DbType="VarChar(20)")] string parentCustomerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telephone", DbType="VarChar(20)")] string telephone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="VarChar(20)")] string fax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(1)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(50)")] string address1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="NVarChar(50)")] string address2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address3", DbType="NVarChar(50)")] string address3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="VarChar(20)")] string createdBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string isSVat, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonName", DbType="VarChar(150)")] string contactPersonName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonDesignation", DbType="VarChar(50)")] string contactPersonDesignation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonDirectPhoneNumber", DbType="VarChar(20)")] string contactPersonDirectPhoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonMobile", DbType="VarChar(20)")] string contactPersonMobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonEmail", DbType="VarChar(50)")] string contactPersonEmail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NCEMember", DbType="VarChar(10)")] string nCEMember)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestId, parentCustomerID, name, telephone, email, fax, status, address1, address2, address3, createdBy, isSVat, contactPersonName, contactPersonDesignation, contactPersonDirectPhoneNumber, contactPersonMobile, contactPersonEmail, nCEMember);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class DCISgetSequenceResult
	{
		
		private System.Nullable<long> _SequesnceValue;
		
		public DCISgetSequenceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SequesnceValue", DbType="BigInt")]
		public System.Nullable<long> SequesnceValue
		{
			get
			{
				return this._SequesnceValue;
			}
			set
			{
				if ((this._SequesnceValue != value))
				{
					this._SequesnceValue = value;
				}
			}
		}
	}
	
	public partial class DCISgetParentCustomerRequestListResult
	{
		
		private string _RequestId;
		
		private string _CustomerName;
		
		private string _Telephone;
		
		private string _IsSVat;
		
		private string _Fax;
		
		private string _Email;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _Status;
		
		private System.DateTime _CreatedDate;
		
		private string _CreatedBy;
		
		private string _ContactPersonName;
		
		private string _ContactPersonDesignation;
		
		private string _ContactPersonDirectPhoneNumber;
		
		private string _ContactPersonMobile;
		
		private string _ContactPersonEmail;
		
		private string _NCEMember;
		
		private string _PaidType;
		
		private string _AdminUserId;
		
		private string _AdminPassword;
		
		private string _AdminName;
		
		public DCISgetParentCustomerRequestListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RequestId
		{
			get
			{
				return this._RequestId;
			}
			set
			{
				if ((this._RequestId != value))
				{
					this._RequestId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSVat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string IsSVat
		{
			get
			{
				return this._IsSVat;
			}
			set
			{
				if ((this._IsSVat != value))
				{
					this._IsSVat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this._Address3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonName", DbType="VarChar(150)")]
		public string ContactPersonName
		{
			get
			{
				return this._ContactPersonName;
			}
			set
			{
				if ((this._ContactPersonName != value))
				{
					this._ContactPersonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonDesignation", DbType="VarChar(50)")]
		public string ContactPersonDesignation
		{
			get
			{
				return this._ContactPersonDesignation;
			}
			set
			{
				if ((this._ContactPersonDesignation != value))
				{
					this._ContactPersonDesignation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonDirectPhoneNumber", DbType="VarChar(20)")]
		public string ContactPersonDirectPhoneNumber
		{
			get
			{
				return this._ContactPersonDirectPhoneNumber;
			}
			set
			{
				if ((this._ContactPersonDirectPhoneNumber != value))
				{
					this._ContactPersonDirectPhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonMobile", DbType="VarChar(20)")]
		public string ContactPersonMobile
		{
			get
			{
				return this._ContactPersonMobile;
			}
			set
			{
				if ((this._ContactPersonMobile != value))
				{
					this._ContactPersonMobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonEmail", DbType="VarChar(50)")]
		public string ContactPersonEmail
		{
			get
			{
				return this._ContactPersonEmail;
			}
			set
			{
				if ((this._ContactPersonEmail != value))
				{
					this._ContactPersonEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCEMember", DbType="VarChar(10)")]
		public string NCEMember
		{
			get
			{
				return this._NCEMember;
			}
			set
			{
				if ((this._NCEMember != value))
				{
					this._NCEMember = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaidType", DbType="VarChar(10)")]
		public string PaidType
		{
			get
			{
				return this._PaidType;
			}
			set
			{
				if ((this._PaidType != value))
				{
					this._PaidType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminUserId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string AdminUserId
		{
			get
			{
				return this._AdminUserId;
			}
			set
			{
				if ((this._AdminUserId != value))
				{
					this._AdminUserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminPassword", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string AdminPassword
		{
			get
			{
				return this._AdminPassword;
			}
			set
			{
				if ((this._AdminPassword != value))
				{
					this._AdminPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminName", DbType="VarChar(150)")]
		public string AdminName
		{
			get
			{
				return this._AdminName;
			}
			set
			{
				if ((this._AdminName != value))
				{
					this._AdminName = value;
				}
			}
		}
	}
	
	public partial class DCISgetParentCustomerRequestDetailsResult
	{
		
		private string _RequestId;
		
		private string _CustomerName;
		
		private string _Telephone;
		
		private string _IsSVat;
		
		private string _Fax;
		
		private string _Email;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _Status;
		
		private System.DateTime _CreatedDate;
		
		private string _CreatedBy;
		
		private string _ContactPersonName;
		
		private string _ContactPersonDesignation;
		
		private string _ContactPersonDirectPhoneNumber;
		
		private string _ContactPersonMobile;
		
		private string _ContactPersonEmail;
		
		private string _NCEMember;
		
		private string _PaidType;
		
		private string _AdminUserId;
		
		private string _AdminPassword;
		
		private string _AdminName;
		
		public DCISgetParentCustomerRequestDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RequestId
		{
			get
			{
				return this._RequestId;
			}
			set
			{
				if ((this._RequestId != value))
				{
					this._RequestId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSVat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string IsSVat
		{
			get
			{
				return this._IsSVat;
			}
			set
			{
				if ((this._IsSVat != value))
				{
					this._IsSVat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this._Address3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonName", DbType="VarChar(150)")]
		public string ContactPersonName
		{
			get
			{
				return this._ContactPersonName;
			}
			set
			{
				if ((this._ContactPersonName != value))
				{
					this._ContactPersonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonDesignation", DbType="VarChar(50)")]
		public string ContactPersonDesignation
		{
			get
			{
				return this._ContactPersonDesignation;
			}
			set
			{
				if ((this._ContactPersonDesignation != value))
				{
					this._ContactPersonDesignation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonDirectPhoneNumber", DbType="VarChar(20)")]
		public string ContactPersonDirectPhoneNumber
		{
			get
			{
				return this._ContactPersonDirectPhoneNumber;
			}
			set
			{
				if ((this._ContactPersonDirectPhoneNumber != value))
				{
					this._ContactPersonDirectPhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonMobile", DbType="VarChar(20)")]
		public string ContactPersonMobile
		{
			get
			{
				return this._ContactPersonMobile;
			}
			set
			{
				if ((this._ContactPersonMobile != value))
				{
					this._ContactPersonMobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonEmail", DbType="VarChar(50)")]
		public string ContactPersonEmail
		{
			get
			{
				return this._ContactPersonEmail;
			}
			set
			{
				if ((this._ContactPersonEmail != value))
				{
					this._ContactPersonEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCEMember", DbType="VarChar(10)")]
		public string NCEMember
		{
			get
			{
				return this._NCEMember;
			}
			set
			{
				if ((this._NCEMember != value))
				{
					this._NCEMember = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaidType", DbType="VarChar(10)")]
		public string PaidType
		{
			get
			{
				return this._PaidType;
			}
			set
			{
				if ((this._PaidType != value))
				{
					this._PaidType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminUserId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string AdminUserId
		{
			get
			{
				return this._AdminUserId;
			}
			set
			{
				if ((this._AdminUserId != value))
				{
					this._AdminUserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminPassword", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string AdminPassword
		{
			get
			{
				return this._AdminPassword;
			}
			set
			{
				if ((this._AdminPassword != value))
				{
					this._AdminPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminName", DbType="VarChar(150)")]
		public string AdminName
		{
			get
			{
				return this._AdminName;
			}
			set
			{
				if ((this._AdminName != value))
				{
					this._AdminName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
