#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCEDCO.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NCEDCO")]
	public partial class DBLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBLinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NCEDCOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISgetSequence")]
		public ISingleResult<DCISgetSequenceResult> DCISgetSequence([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SequenceName", DbType="VarChar(50)")] string sequenceName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sequenceName);
			return ((ISingleResult<DCISgetSequenceResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISsetParentCustomerRequest")]
		public int DCISsetParentCustomerRequest(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestId", DbType="VarChar(20)")] string requestId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telephone", DbType="VarChar(20)")] string telephone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="VarChar(20)")] string fax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(1)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(50)")] string address1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="NVarChar(50)")] string address2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address3", DbType="NVarChar(50)")] string address3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="VarChar(20)")] string createdBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string isSVat, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserId", DbType="VarChar(20)")] string adminUserId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminPassword", DbType="VarChar(200)")] string adminPassword, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonName", DbType="VarChar(150)")] string contactPersonName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonDesignation", DbType="VarChar(50)")] string contactPersonDesignation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonDirectPhoneNumber", DbType="VarChar(20)")] string contactPersonDirectPhoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonMobile", DbType="VarChar(20)")] string contactPersonMobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonEmail", DbType="VarChar(50)")] string contactPersonEmail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NCEMember", DbType="VarChar(10)")] string nCEMember, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminName", DbType="VarChar(150)")] string adminName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestId, name, telephone, email, fax, status, address1, address2, address3, createdBy, isSVat, adminUserId, adminPassword, contactPersonName, contactPersonDesignation, contactPersonDirectPhoneNumber, contactPersonMobile, contactPersonEmail, nCEMember, adminName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISgetParentCustomerRequestList")]
		public ISingleResult<DCISgetParentCustomerRequestListResult> DCISgetParentCustomerRequestList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(5)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), status);
			return ((ISingleResult<DCISgetParentCustomerRequestListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISgetParentCustomerRequestDetails")]
		public ISingleResult<DCISgetParentCustomerRequestDetailsResult> DCISgetParentCustomerRequestDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestID", DbType="VarChar(20)")] string requestID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestID);
			return ((ISingleResult<DCISgetParentCustomerRequestDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISsetUpdateParentCustomerReq")]
		public int DCISsetUpdateParentCustomerReq([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(1)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestID", DbType="VarChar(20)")] string requestID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), status, requestID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISsetApproveParentCustomer")]
		public int DCISsetApproveParentCustomer(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestId", DbType="VarChar(20)")] string requestId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentCustomerID", DbType="VarChar(20)")] string parentCustomerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telephone", DbType="VarChar(20)")] string telephone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="VarChar(20)")] string fax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(1)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(50)")] string address1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="NVarChar(50)")] string address2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address3", DbType="NVarChar(50)")] string address3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="VarChar(20)")] string createdBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string isSVat, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonName", DbType="VarChar(150)")] string contactPersonName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonDesignation", DbType="VarChar(50)")] string contactPersonDesignation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonDirectPhoneNumber", DbType="VarChar(20)")] string contactPersonDirectPhoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonMobile", DbType="VarChar(20)")] string contactPersonMobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonEmail", DbType="VarChar(50)")] string contactPersonEmail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NCEMember", DbType="VarChar(10)")] string nCEMember)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestId, parentCustomerID, name, telephone, email, fax, status, address1, address2, address3, createdBy, isSVat, contactPersonName, contactPersonDesignation, contactPersonDirectPhoneNumber, contactPersonMobile, contactPersonEmail, nCEMember);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISgeMailParameters")]
		public ISingleResult<DCISgeMailParametersResult> DCISgeMailParameters()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DCISgeMailParametersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISsetCustomerParentReject")]
		public int DCISsetCustomerParentReject([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestId", DbType="VarChar(20)")] string requestId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getRejectReasons]")]
		public ISingleResult<_getRejectReasonsResult> _getRejectReasons([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RejectReasonCategory", DbType="VarChar(20)")] string rejectReasonCategory)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rejectReasonCategory);
			return ((ISingleResult<_getRejectReasonsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISsetApprovedPCUser")]
		public int DCISsetApprovedPCUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="VarChar(20)")] string userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonName", DbType="VarChar(150)")] string personName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(200)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentCustomerId", DbType="VarChar(20)")] string parentCustomerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, personName, password, parentCustomerId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getAllExportSector]")]
		public ISingleResult<_getAllExportSectorResult> _getAllExportSector([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(1)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), status);
			return ((ISingleResult<_getAllExportSectorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_setParentChildCustomerRequest]")]
		public int _setParentChildCustomerRequest(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestId", DbType="VarChar(20)")] string requestId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telephone", DbType="VarChar(20)")] string telephone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="VarChar(20)")] string fax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(1)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(50)")] string address1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="NVarChar(50)")] string address2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address3", DbType="NVarChar(50)")] string address3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="VarChar(20)")] string createdBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string isSVat, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonName", DbType="VarChar(150)")] string contactPersonName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonDesignation", DbType="VarChar(50)")] string contactPersonDesignation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonDirectPhoneNumber", DbType="VarChar(20)")] string contactPersonDirectPhoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonMobile", DbType="VarChar(20)")] string contactPersonMobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonEmail", DbType="VarChar(50)")] string contactPersonEmail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NCEMember", DbType="VarChar(10)")] string nCEMember, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentCustomerId", DbType="VarChar(20)")] string parentCustomerId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductDetails", DbType="Text")] string productDetails, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExportSector", DbType="VarChar(100)")] string exportSector)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestId, name, telephone, email, fax, status, address1, address2, address3, createdBy, isSVat, contactPersonName, contactPersonDesignation, contactPersonDirectPhoneNumber, contactPersonMobile, contactPersonEmail, nCEMember, parentCustomerId, productDetails, exportSector);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DCISgetTemplateHeader")]
		public ISingleResult<DCISgetTemplateHeaderResult> DCISgetTemplateHeader([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemplateId", DbType="VarChar(20)")] string templateId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="VarChar(2)")] string isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminOnlyDisplay", DbType="VarChar(2)")] string adminOnlyDisplay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), templateId, isActive, adminOnlyDisplay);
			return ((ISingleResult<DCISgetTemplateHeaderResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_setCutomerClientTemplate]")]
		public int _setCutomerClientTemplate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestId", DbType="VarChar(20)")] string requestId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemplateId", DbType="VarChar(20)")] string templateId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestId, templateId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getUserlogin]")]
		public ISingleResult<_getUserloginResult> _getUserlogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="VarChar(20)")] string userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, password);
			return ((ISingleResult<_getUserloginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getUserName]")]
		public ISingleResult<_getUserNameResult> _getUserName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId);
			return ((ISingleResult<_getUserNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getClientCustomerRequestList]")]
		public ISingleResult<_getClientCustomerRequestListResult> _getClientCustomerRequestList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(5)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), status);
			return ((ISingleResult<_getClientCustomerRequestListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getClientCustomerRequestDetails]")]
		public ISingleResult<_getClientCustomerRequestDetailsResult> _getClientCustomerRequestDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestID", DbType="VarChar(20)")] string requestID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestID);
			return ((ISingleResult<_getClientCustomerRequestDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_setApproveChildCustomer]")]
		public int _setApproveChildCustomer(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestId", DbType="VarChar(20)")] string requestId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentCustomerID", DbType="VarChar(20)")] string parentCustomerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChildCustomeID", DbType="VarChar(20)")] string childCustomeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telephone", DbType="VarChar(20)")] string telephone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="VarChar(20)")] string fax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(1)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(50)")] string address1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="NVarChar(50)")] string address2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address3", DbType="NVarChar(50)")] string address3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="VarChar(20)")] string createdBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string isSVat, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonName", DbType="VarChar(150)")] string contactPersonName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonDesignation", DbType="VarChar(50)")] string contactPersonDesignation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonDirectPhoneNumber", DbType="VarChar(20)")] string contactPersonDirectPhoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonMobile", DbType="VarChar(20)")] string contactPersonMobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactPersonEmail", DbType="VarChar(50)")] string contactPersonEmail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NCEMember", DbType="VarChar(10)")] string nCEMember, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductDetails", DbType="Text")] string productDetails, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExportSector", DbType="VarChar(200)")] string exportSector)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestId, parentCustomerID, childCustomeID, name, telephone, email, fax, status, address1, address2, address3, createdBy, isSVat, contactPersonName, contactPersonDesignation, contactPersonDirectPhoneNumber, contactPersonMobile, contactPersonEmail, nCEMember, productDetails, exportSector);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_setUpdateClientCustomerReq]")]
		public int _setUpdateClientCustomerReq([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(1)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestID", DbType="VarChar(20)")] string requestID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), status, requestID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_setCustomerChildReject]")]
		public int _setCustomerChildReject([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestId", DbType="VarChar(20)")] string requestId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getUserGroupFunction]")]
		public ISingleResult<_getUserGroupFunctionResult> _getUserGroupFunction([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FunctionId", DbType="VarChar(20)")] string functionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GroupId", DbType="VarChar(20)")] string groupId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), functionId, groupId);
			return ((ISingleResult<_getUserGroupFunctionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_setUpdateOwnerContact]")]
		public int _setUpdateOwnerContact([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string web, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string fax)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, phone, email, web, fax);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getOwnerContact]")]
		public ISingleResult<_getOwnerContactResult> _getOwnerContact()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<_getOwnerContactResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getOwnerCompany]")]
		public ISingleResult<_getOwnerCompanyResult> _getOwnerCompany()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<_getOwnerCompanyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_setUpdateOwnerCompany]")]
		public int _setUpdateOwnerCompany([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrganizationName", DbType="VarChar(150)")] string organizationName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostBox", DbType="VarChar(40)")] string postBox, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="VarChar(120)")] string address1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="VarChar(120)")] string address2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address3", DbType="VarChar(50)")] string address3)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), organizationName, postBox, address1, address2, address3);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_setSupportingDocuments]")]
		public int _setSupportingDocuments([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupportingDocumentId", DbType="VarChar(20)")] string supportingDocumentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupportingDocumentName", DbType="NVarChar(100)")] string supportingDocumentName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="NVarChar(50)")] string createdBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="VarChar(2)")] string isActive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), supportingDocumentId, supportingDocumentName, createdBy, isActive);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_setUpdateSupportingDocuments]")]
		public int _setUpdateSupportingDocuments([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupportingDocumentId", DbType="VarChar(20)")] string supportingDocumentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupportingDocumentName", DbType="VarChar(100)")] string supportingDocumentName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="VarChar(20)")] string modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), supportingDocumentId, supportingDocumentName, modifiedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_setDeleteSupportingDocuments]")]
		public int _setDeleteSupportingDocuments([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupportingDocumentId", DbType="VarChar(20)")] string supportingDocumentId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), supportingDocumentId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_getSupportDocument]")]
		public ISingleResult<_getSupportDocumentResult> _getSupportDocument([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupportingDocumentId", DbType="VarChar(20)")] string supportingDocumentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="VarChar(1)")] string isActive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), supportingDocumentId, isActive);
			return ((ISingleResult<_getSupportDocumentResult>)(result.ReturnValue));
		}
	}
	
	public partial class DCISgetSequenceResult
	{
		
		private System.Nullable<long> _SequesnceValue;
		
		public DCISgetSequenceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SequesnceValue", DbType="BigInt")]
		public System.Nullable<long> SequesnceValue
		{
			get
			{
				return this._SequesnceValue;
			}
			set
			{
				if ((this._SequesnceValue != value))
				{
					this._SequesnceValue = value;
				}
			}
		}
	}
	
	public partial class DCISgetParentCustomerRequestListResult
	{
		
		private string _RequestId;
		
		private string _CustomerName;
		
		private string _Telephone;
		
		private string _IsSVat;
		
		private string _Fax;
		
		private string _Email;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _Status;
		
		private System.DateTime _CreatedDate;
		
		private string _CreatedBy;
		
		private string _ContactPersonName;
		
		private string _ContactPersonDesignation;
		
		private string _ContactPersonDirectPhoneNumber;
		
		private string _ContactPersonMobile;
		
		private string _ContactPersonEmail;
		
		private string _NCEMember;
		
		private string _PaidType;
		
		private string _AdminUserId;
		
		private string _AdminPassword;
		
		private string _AdminName;
		
		public DCISgetParentCustomerRequestListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RequestId
		{
			get
			{
				return this._RequestId;
			}
			set
			{
				if ((this._RequestId != value))
				{
					this._RequestId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSVat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string IsSVat
		{
			get
			{
				return this._IsSVat;
			}
			set
			{
				if ((this._IsSVat != value))
				{
					this._IsSVat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this._Address3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonName", DbType="VarChar(150)")]
		public string ContactPersonName
		{
			get
			{
				return this._ContactPersonName;
			}
			set
			{
				if ((this._ContactPersonName != value))
				{
					this._ContactPersonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonDesignation", DbType="VarChar(50)")]
		public string ContactPersonDesignation
		{
			get
			{
				return this._ContactPersonDesignation;
			}
			set
			{
				if ((this._ContactPersonDesignation != value))
				{
					this._ContactPersonDesignation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonDirectPhoneNumber", DbType="VarChar(20)")]
		public string ContactPersonDirectPhoneNumber
		{
			get
			{
				return this._ContactPersonDirectPhoneNumber;
			}
			set
			{
				if ((this._ContactPersonDirectPhoneNumber != value))
				{
					this._ContactPersonDirectPhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonMobile", DbType="VarChar(20)")]
		public string ContactPersonMobile
		{
			get
			{
				return this._ContactPersonMobile;
			}
			set
			{
				if ((this._ContactPersonMobile != value))
				{
					this._ContactPersonMobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonEmail", DbType="VarChar(50)")]
		public string ContactPersonEmail
		{
			get
			{
				return this._ContactPersonEmail;
			}
			set
			{
				if ((this._ContactPersonEmail != value))
				{
					this._ContactPersonEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCEMember", DbType="VarChar(10)")]
		public string NCEMember
		{
			get
			{
				return this._NCEMember;
			}
			set
			{
				if ((this._NCEMember != value))
				{
					this._NCEMember = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaidType", DbType="VarChar(10)")]
		public string PaidType
		{
			get
			{
				return this._PaidType;
			}
			set
			{
				if ((this._PaidType != value))
				{
					this._PaidType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminUserId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string AdminUserId
		{
			get
			{
				return this._AdminUserId;
			}
			set
			{
				if ((this._AdminUserId != value))
				{
					this._AdminUserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminPassword", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string AdminPassword
		{
			get
			{
				return this._AdminPassword;
			}
			set
			{
				if ((this._AdminPassword != value))
				{
					this._AdminPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminName", DbType="VarChar(150)")]
		public string AdminName
		{
			get
			{
				return this._AdminName;
			}
			set
			{
				if ((this._AdminName != value))
				{
					this._AdminName = value;
				}
			}
		}
	}
	
	public partial class DCISgetParentCustomerRequestDetailsResult
	{
		
		private string _RequestId;
		
		private string _CustomerName;
		
		private string _Telephone;
		
		private string _IsSVat;
		
		private string _Fax;
		
		private string _Email;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _Status;
		
		private System.DateTime _CreatedDate;
		
		private string _CreatedBy;
		
		private string _ContactPersonName;
		
		private string _ContactPersonDesignation;
		
		private string _ContactPersonDirectPhoneNumber;
		
		private string _ContactPersonMobile;
		
		private string _ContactPersonEmail;
		
		private string _NCEMember;
		
		private string _PaidType;
		
		private string _AdminUserId;
		
		private string _AdminPassword;
		
		private string _AdminName;
		
		public DCISgetParentCustomerRequestDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RequestId
		{
			get
			{
				return this._RequestId;
			}
			set
			{
				if ((this._RequestId != value))
				{
					this._RequestId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSVat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string IsSVat
		{
			get
			{
				return this._IsSVat;
			}
			set
			{
				if ((this._IsSVat != value))
				{
					this._IsSVat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this._Address3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonName", DbType="VarChar(150)")]
		public string ContactPersonName
		{
			get
			{
				return this._ContactPersonName;
			}
			set
			{
				if ((this._ContactPersonName != value))
				{
					this._ContactPersonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonDesignation", DbType="VarChar(50)")]
		public string ContactPersonDesignation
		{
			get
			{
				return this._ContactPersonDesignation;
			}
			set
			{
				if ((this._ContactPersonDesignation != value))
				{
					this._ContactPersonDesignation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonDirectPhoneNumber", DbType="VarChar(20)")]
		public string ContactPersonDirectPhoneNumber
		{
			get
			{
				return this._ContactPersonDirectPhoneNumber;
			}
			set
			{
				if ((this._ContactPersonDirectPhoneNumber != value))
				{
					this._ContactPersonDirectPhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonMobile", DbType="VarChar(20)")]
		public string ContactPersonMobile
		{
			get
			{
				return this._ContactPersonMobile;
			}
			set
			{
				if ((this._ContactPersonMobile != value))
				{
					this._ContactPersonMobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonEmail", DbType="VarChar(50)")]
		public string ContactPersonEmail
		{
			get
			{
				return this._ContactPersonEmail;
			}
			set
			{
				if ((this._ContactPersonEmail != value))
				{
					this._ContactPersonEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCEMember", DbType="VarChar(10)")]
		public string NCEMember
		{
			get
			{
				return this._NCEMember;
			}
			set
			{
				if ((this._NCEMember != value))
				{
					this._NCEMember = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaidType", DbType="VarChar(10)")]
		public string PaidType
		{
			get
			{
				return this._PaidType;
			}
			set
			{
				if ((this._PaidType != value))
				{
					this._PaidType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminUserId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string AdminUserId
		{
			get
			{
				return this._AdminUserId;
			}
			set
			{
				if ((this._AdminUserId != value))
				{
					this._AdminUserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminPassword", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string AdminPassword
		{
			get
			{
				return this._AdminPassword;
			}
			set
			{
				if ((this._AdminPassword != value))
				{
					this._AdminPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminName", DbType="VarChar(150)")]
		public string AdminName
		{
			get
			{
				return this._AdminName;
			}
			set
			{
				if ((this._AdminName != value))
				{
					this._AdminName = value;
				}
			}
		}
	}
	
	public partial class DCISgeMailParametersResult
	{
		
		private string _ParameterCode;
		
		private string _ParameterValue;
		
		public DCISgeMailParametersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParameterCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ParameterCode
		{
			get
			{
				return this._ParameterCode;
			}
			set
			{
				if ((this._ParameterCode != value))
				{
					this._ParameterCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParameterValue", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ParameterValue
		{
			get
			{
				return this._ParameterValue;
			}
			set
			{
				if ((this._ParameterValue != value))
				{
					this._ParameterValue = value;
				}
			}
		}
	}
	
	public partial class _getRejectReasonsResult
	{
		
		private string _RejectCode;
		
		private string _ReasonName;
		
		public _getRejectReasonsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RejectCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RejectCode
		{
			get
			{
				return this._RejectCode;
			}
			set
			{
				if ((this._RejectCode != value))
				{
					this._RejectCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string ReasonName
		{
			get
			{
				return this._ReasonName;
			}
			set
			{
				if ((this._ReasonName != value))
				{
					this._ReasonName = value;
				}
			}
		}
	}
	
	public partial class _getAllExportSectorResult
	{
		
		private string _ExportSector;
		
		private string _ExportId;
		
		public _getAllExportSectorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExportSector", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ExportSector
		{
			get
			{
				return this._ExportSector;
			}
			set
			{
				if ((this._ExportSector != value))
				{
					this._ExportSector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExportId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ExportId
		{
			get
			{
				return this._ExportId;
			}
			set
			{
				if ((this._ExportId != value))
				{
					this._ExportId = value;
				}
			}
		}
	}
	
	public partial class DCISgetTemplateHeaderResult
	{
		
		private string _TemplateId;
		
		private string _TemplateName;
		
		private string _ImgUrl;
		
		private System.DateTime _CreatedDate;
		
		private System.DateTime _ModifiedDate;
		
		private string _IsActive;
		
		private string _ModifiedBy;
		
		private string _CreatedBy;
		
		private string _Description;
		
		private string _TemplatePath;
		
		public DCISgetTemplateHeaderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TemplateId
		{
			get
			{
				return this._TemplateId;
			}
			set
			{
				if ((this._TemplateId != value))
				{
					this._TemplateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TemplateName
		{
			get
			{
				return this._TemplateName;
			}
			set
			{
				if ((this._TemplateName != value))
				{
					this._TemplateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgUrl", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string ImgUrl
		{
			get
			{
				return this._ImgUrl;
			}
			set
			{
				if ((this._ImgUrl != value))
				{
					this._ImgUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime NOT NULL")]
		public System.DateTime ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this._ModifiedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this._ModifiedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplatePath", DbType="VarChar(250)")]
		public string TemplatePath
		{
			get
			{
				return this._TemplatePath;
			}
			set
			{
				if ((this._TemplatePath != value))
				{
					this._TemplatePath = value;
				}
			}
		}
	}
	
	public partial class _getUserloginResult
	{
		
		private string _UserId;
		
		private string _UserGroupID;
		
		private string _IsActive;
		
		private string _Password;
		
		private System.DateTime _PassowordExpiryDate;
		
		private string _PersonName;
		
		private string _ParentCustomerId;
		
		public _getUserloginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserGroupID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UserGroupID
		{
			get
			{
				return this._UserGroupID;
			}
			set
			{
				if ((this._UserGroupID != value))
				{
					this._UserGroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassowordExpiryDate", DbType="DateTime NOT NULL")]
		public System.DateTime PassowordExpiryDate
		{
			get
			{
				return this._PassowordExpiryDate;
			}
			set
			{
				if ((this._PassowordExpiryDate != value))
				{
					this._PassowordExpiryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string PersonName
		{
			get
			{
				return this._PersonName;
			}
			set
			{
				if ((this._PersonName != value))
				{
					this._PersonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCustomerId", DbType="VarChar(20)")]
		public string ParentCustomerId
		{
			get
			{
				return this._ParentCustomerId;
			}
			set
			{
				if ((this._ParentCustomerId != value))
				{
					this._ParentCustomerId = value;
				}
			}
		}
	}
	
	public partial class _getUserNameResult
	{
		
		private string _UserID;
		
		public _getUserNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
	}
	
	public partial class _getClientCustomerRequestListResult
	{
		
		private string _RequestId;
		
		private string _Name;
		
		private string _Telephone;
		
		private string _SVat;
		
		private string _Fax;
		
		private string _Email;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _CreatedBy;
		
		private string _ContactPersonName;
		
		private string _ContactPersonDesignation;
		
		private string _ContactPersonDirectPhoneNumber;
		
		private string _ContactPersonMobile;
		
		private string _ContactPersonEmail;
		
		private string _NCEMember;
		
		private System.Nullable<System.DateTime> _CreatedDate1;
		
		public _getClientCustomerRequestListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RequestId
		{
			get
			{
				return this._RequestId;
			}
			set
			{
				if ((this._RequestId != value))
				{
					this._RequestId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SVat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SVat
		{
			get
			{
				return this._SVat;
			}
			set
			{
				if ((this._SVat != value))
				{
					this._SVat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(150)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="VarChar(150)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this._Address3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(20)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonName", DbType="VarChar(150)")]
		public string ContactPersonName
		{
			get
			{
				return this._ContactPersonName;
			}
			set
			{
				if ((this._ContactPersonName != value))
				{
					this._ContactPersonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonDesignation", DbType="VarChar(50)")]
		public string ContactPersonDesignation
		{
			get
			{
				return this._ContactPersonDesignation;
			}
			set
			{
				if ((this._ContactPersonDesignation != value))
				{
					this._ContactPersonDesignation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonDirectPhoneNumber", DbType="VarChar(20)")]
		public string ContactPersonDirectPhoneNumber
		{
			get
			{
				return this._ContactPersonDirectPhoneNumber;
			}
			set
			{
				if ((this._ContactPersonDirectPhoneNumber != value))
				{
					this._ContactPersonDirectPhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonMobile", DbType="VarChar(20)")]
		public string ContactPersonMobile
		{
			get
			{
				return this._ContactPersonMobile;
			}
			set
			{
				if ((this._ContactPersonMobile != value))
				{
					this._ContactPersonMobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonEmail", DbType="VarChar(50)")]
		public string ContactPersonEmail
		{
			get
			{
				return this._ContactPersonEmail;
			}
			set
			{
				if ((this._ContactPersonEmail != value))
				{
					this._ContactPersonEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCEMember", DbType="VarChar(10)")]
		public string NCEMember
		{
			get
			{
				return this._NCEMember;
			}
			set
			{
				if ((this._NCEMember != value))
				{
					this._NCEMember = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate1", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate1
		{
			get
			{
				return this._CreatedDate1;
			}
			set
			{
				if ((this._CreatedDate1 != value))
				{
					this._CreatedDate1 = value;
				}
			}
		}
	}
	
	public partial class _getClientCustomerRequestDetailsResult
	{
		
		private string _RequestId;
		
		private string _Name;
		
		private string _Telephone;
		
		private string _SVat;
		
		private string _Fax;
		
		private string _Email;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _CreatedBy;
		
		private string _ContactPersonName;
		
		private string _ContactPersonDesignation;
		
		private string _ContactPersonDirectPhoneNumber;
		
		private string _ContactPersonMobile;
		
		private string _ContactPersonEmail;
		
		private string _NCEMember;
		
		private string _TemplateId;
		
		private string _TemplateName;
		
		private string _Productdetails;
		
		private string _ExportSector;
		
		private string _ExportSectorName;
		
		private string _ParentCustomerId;
		
		private string _CustomerName;
		
		public _getClientCustomerRequestDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RequestId
		{
			get
			{
				return this._RequestId;
			}
			set
			{
				if ((this._RequestId != value))
				{
					this._RequestId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SVat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SVat
		{
			get
			{
				return this._SVat;
			}
			set
			{
				if ((this._SVat != value))
				{
					this._SVat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(150)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="VarChar(150)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this._Address3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(20)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonName", DbType="VarChar(150)")]
		public string ContactPersonName
		{
			get
			{
				return this._ContactPersonName;
			}
			set
			{
				if ((this._ContactPersonName != value))
				{
					this._ContactPersonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonDesignation", DbType="VarChar(50)")]
		public string ContactPersonDesignation
		{
			get
			{
				return this._ContactPersonDesignation;
			}
			set
			{
				if ((this._ContactPersonDesignation != value))
				{
					this._ContactPersonDesignation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonDirectPhoneNumber", DbType="VarChar(20)")]
		public string ContactPersonDirectPhoneNumber
		{
			get
			{
				return this._ContactPersonDirectPhoneNumber;
			}
			set
			{
				if ((this._ContactPersonDirectPhoneNumber != value))
				{
					this._ContactPersonDirectPhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonMobile", DbType="VarChar(20)")]
		public string ContactPersonMobile
		{
			get
			{
				return this._ContactPersonMobile;
			}
			set
			{
				if ((this._ContactPersonMobile != value))
				{
					this._ContactPersonMobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonEmail", DbType="VarChar(50)")]
		public string ContactPersonEmail
		{
			get
			{
				return this._ContactPersonEmail;
			}
			set
			{
				if ((this._ContactPersonEmail != value))
				{
					this._ContactPersonEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCEMember", DbType="VarChar(10)")]
		public string NCEMember
		{
			get
			{
				return this._NCEMember;
			}
			set
			{
				if ((this._NCEMember != value))
				{
					this._NCEMember = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateId", DbType="VarChar(20)")]
		public string TemplateId
		{
			get
			{
				return this._TemplateId;
			}
			set
			{
				if ((this._TemplateId != value))
				{
					this._TemplateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TemplateName
		{
			get
			{
				return this._TemplateName;
			}
			set
			{
				if ((this._TemplateName != value))
				{
					this._TemplateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Productdetails", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Productdetails
		{
			get
			{
				return this._Productdetails;
			}
			set
			{
				if ((this._Productdetails != value))
				{
					this._Productdetails = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExportSector", DbType="VarChar(100)")]
		public string ExportSector
		{
			get
			{
				return this._ExportSector;
			}
			set
			{
				if ((this._ExportSector != value))
				{
					this._ExportSector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExportSectorName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ExportSectorName
		{
			get
			{
				return this._ExportSectorName;
			}
			set
			{
				if ((this._ExportSectorName != value))
				{
					this._ExportSectorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCustomerId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ParentCustomerId
		{
			get
			{
				return this._ParentCustomerId;
			}
			set
			{
				if ((this._ParentCustomerId != value))
				{
					this._ParentCustomerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
	}
	
	public partial class _getUserGroupFunctionResult
	{
		
		private string _FunctionId;
		
		private string _GroupId;
		
		public _getUserGroupFunctionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FunctionId", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string FunctionId
		{
			get
			{
				return this._FunctionId;
			}
			set
			{
				if ((this._FunctionId != value))
				{
					this._FunctionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this._GroupId = value;
				}
			}
		}
	}
	
	public partial class _getOwnerContactResult
	{
		
		private string _Email;
		
		private string _FaxNo;
		
		private string _Name;
		
		private string _TelephoneNo;
		
		private string _WebAddress;
		
		public _getOwnerContactResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxNo", DbType="VarChar(15)")]
		public string FaxNo
		{
			get
			{
				return this._FaxNo;
			}
			set
			{
				if ((this._FaxNo != value))
				{
					this._FaxNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(150)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelephoneNo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TelephoneNo
		{
			get
			{
				return this._TelephoneNo;
			}
			set
			{
				if ((this._TelephoneNo != value))
				{
					this._TelephoneNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebAddress", DbType="VarChar(150)")]
		public string WebAddress
		{
			get
			{
				return this._WebAddress;
			}
			set
			{
				if ((this._WebAddress != value))
				{
					this._WebAddress = value;
				}
			}
		}
	}
	
	public partial class _getOwnerCompanyResult
	{
		
		private string _OrganizationName;
		
		private string _PostBox;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		public _getOwnerCompanyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganizationName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string OrganizationName
		{
			get
			{
				return this._OrganizationName;
			}
			set
			{
				if ((this._OrganizationName != value))
				{
					this._OrganizationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostBox", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PostBox
		{
			get
			{
				return this._PostBox;
			}
			set
			{
				if ((this._PostBox != value))
				{
					this._PostBox = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(120)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(120)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this._Address3 = value;
				}
			}
		}
	}
	
	public partial class _getSupportDocumentResult
	{
		
		private string _SupportingDocumentId;
		
		private string _CreatedBy;
		
		private System.DateTime _CreatedDate;
		
		private string _IsMandatory;
		
		private string _IsActive;
		
		private string _SupportingDocumentName;
		
		private string _ModifiedBy;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		public _getSupportDocumentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupportingDocumentId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SupportingDocumentId
		{
			get
			{
				return this._SupportingDocumentId;
			}
			set
			{
				if ((this._SupportingDocumentId != value))
				{
					this._SupportingDocumentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMandatory", DbType="VarChar(2)")]
		public string IsMandatory
		{
			get
			{
				return this._IsMandatory;
			}
			set
			{
				if ((this._IsMandatory != value))
				{
					this._IsMandatory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="VarChar(2)")]
		public string IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupportingDocumentName", DbType="VarChar(100)")]
		public string SupportingDocumentName
		{
			get
			{
				return this._SupportingDocumentName;
			}
			set
			{
				if ((this._SupportingDocumentName != value))
				{
					this._SupportingDocumentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="VarChar(20)")]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this._ModifiedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="Date")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this._ModifiedDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
