<?xml version="1.0" encoding="utf-8"?><Database Name="NCEDCO" Class="DBLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ANONYMUS;Initial Catalog=NCEDCO;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NCEDCOConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.DCISgetSequence" Method="DCISgetSequence">
    <Parameter Name="SequenceName" Parameter="sequenceName" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="DCISgetSequenceResult">
      <Column Name="SequesnceValue" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DCISsetParentCustomerRequest" Method="DCISsetParentCustomerRequest">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="Address1" Parameter="address1" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address2" Parameter="address2" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address3" Parameter="address3" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="isSVat" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="AdminUserId" Parameter="adminUserId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="AdminPassword" Parameter="adminPassword" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="ContactPersonName" Parameter="contactPersonName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="ContactPersonDesignation" Parameter="contactPersonDesignation" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ContactPersonDirectPhoneNumber" Parameter="contactPersonDirectPhoneNumber" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ContactPersonMobile" Parameter="contactPersonMobile" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ContactPersonEmail" Parameter="contactPersonEmail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NCEMember" Parameter="nCEMember" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="AdminName" Parameter="adminName" Type="System.String" DbType="VarChar(150)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DCISgetParentCustomerRequestList" Method="DCISgetParentCustomerRequestList">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(5)" />
    <ElementType Name="DCISgetParentCustomerRequestListResult">
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsSVat" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPersonName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ContactPersonDesignation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactPersonDirectPhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonMobile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NCEMember" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PaidType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AdminUserId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AdminPassword" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="AdminName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DCISgetParentCustomerRequestDetails" Method="DCISgetParentCustomerRequestDetails">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="DCISgetParentCustomerRequestDetailsResult">
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsSVat" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPersonName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ContactPersonDesignation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactPersonDirectPhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonMobile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NCEMember" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PaidType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AdminUserId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AdminPassword" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="AdminName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DCISsetUpdateParentCustomerReq" Method="DCISsetUpdateParentCustomerReq">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DCISsetApproveParentCustomer" Method="DCISsetApproveParentCustomer">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ParentCustomerID" Parameter="parentCustomerID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="Address1" Parameter="address1" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address2" Parameter="address2" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address3" Parameter="address3" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="isSVat" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ContactPersonName" Parameter="contactPersonName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="ContactPersonDesignation" Parameter="contactPersonDesignation" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ContactPersonDirectPhoneNumber" Parameter="contactPersonDirectPhoneNumber" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ContactPersonMobile" Parameter="contactPersonMobile" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ContactPersonEmail" Parameter="contactPersonEmail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NCEMember" Parameter="nCEMember" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DCISgeMailParameters" Method="DCISgeMailParameters">
    <ElementType Name="DCISgeMailParametersResult">
      <Column Name="ParameterCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ParameterValue" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.DCISsetCustomerParentReject" Method="DCISsetCustomerParentReject">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getRejectReasons]" Method="_getRejectReasons">
    <Parameter Name="RejectReasonCategory" Parameter="rejectReasonCategory" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getRejectReasonsResult">
      <Column Name="RejectCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ReasonName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.DCISsetApprovedPCUser" Method="DCISsetApprovedPCUser">
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PersonName" Parameter="personName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="ParentCustomerId" Parameter="parentCustomerId" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DCISgetTemplateHeader" Method="DCISgetTemplateHeader">
    <Parameter Name="TemplateId" Parameter="templateId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="AdminOnlyDisplay" Parameter="adminOnlyDisplay" Type="System.String" DbType="VarChar(2)" />
    <ElementType Name="DCISgetTemplateHeaderResult">
      <Column Name="TemplateId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImgUrl" Type="System.String" DbType="NChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TemplatePath" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setCutomerClientTemplate]" Method="_setCutomerClientTemplate">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="TemplateId" Parameter="templateId" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getUserlogin]" Method="_getUserlogin">
    <Parameter Name="UserId" Parameter="userId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="_getUserloginResult">
      <Column Name="UserId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UserGroupID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PassowordExpiryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PersonName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ParentCustomerId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getUserName]" Method="_getUserName">
    <Parameter Name="userId" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getUserNameResult">
      <Column Name="UserID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getClientCustomerRequestList]" Method="_getClientCustomerRequestList">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(5)" />
    <ElementType Name="_getClientCustomerRequestListResult">
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SVat" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ContactPersonDesignation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactPersonDirectPhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonMobile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NCEMember" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CreatedDate1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setUpdateClientCustomerReq]" Method="_setUpdateClientCustomerReq">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setCustomerChildReject]" Method="_setCustomerChildReject">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getUserGroupFunction]" Method="_getUserGroupFunction">
    <Parameter Name="FunctionId" Parameter="functionId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="GroupId" Parameter="groupId" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getUserGroupFunctionResult">
      <Column Name="FunctionId" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setUpdateOwnerContact]" Method="_setUpdateOwnerContact">
    <Parameter Name="name" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="phone" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="web" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="fax" Type="System.String" DbType="VarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getOwnerContact]" Method="_getOwnerContact">
    <ElementType Name="_getOwnerContactResult">
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FaxNo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="TelephoneNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="WebAddress" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getOwnerCompany]" Method="_getOwnerCompany">
    <ElementType Name="_getOwnerCompanyResult">
      <Column Name="OrganizationName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="PostBox" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setUpdateOwnerCompany]" Method="_setUpdateOwnerCompany">
    <Parameter Name="OrganizationName" Parameter="organizationName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="PostBox" Parameter="postBox" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="Address1" Parameter="address1" Type="System.String" DbType="VarChar(120)" />
    <Parameter Name="Address2" Parameter="address2" Type="System.String" DbType="VarChar(120)" />
    <Parameter Name="Address3" Parameter="address3" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setSupportingDocuments]" Method="_setSupportingDocuments">
    <Parameter Name="SupportingDocumentId" Parameter="supportingDocumentId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SupportingDocumentName" Parameter="supportingDocumentName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.String" DbType="VarChar(2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setUpdateSupportingDocuments]" Method="_setUpdateSupportingDocuments">
    <Parameter Name="SupportingDocumentId" Parameter="supportingDocumentId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SupportingDocumentName" Parameter="supportingDocumentName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ModifiedBy" Parameter="modifiedBy" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setDeleteSupportingDocuments]" Method="_setDeleteSupportingDocuments">
    <Parameter Name="SupportingDocumentId" Parameter="supportingDocumentId" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getSupportDocument]" Method="_getSupportDocument">
    <Parameter Name="SupportingDocumentId" Parameter="supportingDocumentId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="_getSupportDocumentResult">
      <Column Name="SupportingDocumentId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsMandatory" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="SupportingDocumentName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setNewExportSector]" Method="_setNewExportSector">
    <Parameter Name="ExportSectorName" Parameter="exportSectorName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setUpdateExportSector]" Method="_setUpdateExportSector">
    <Parameter Name="ExportId" Parameter="exportId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ExportSector" Parameter="exportSector" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.String" DbType="VarChar(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setDeleteExportSector]" Method="_setDeleteExportSector">
    <Parameter Name="ExportID" Parameter="exportID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getExportSector]" Method="_getExportSector">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(5)" />
    <ElementType Name="_getExportSectorResult">
      <Column Name="ExportId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExportSector" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getRejectReasons_List]" Method="_getRejectReasons_List">
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="_getRejectReasons_ListResult">
      <Column Name="RejectCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ReasonName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setNewRejectReason]" Method="_setNewRejectReason">
    <Parameter Name="RejectCode" Parameter="rejectCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ReasonName" Parameter="reasonName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Createdby" Parameter="createdby" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.String" DbType="VarChar(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getRejectReasonCategories]" Method="_getRejectReasonCategories">
    <ElementType Name="_getRejectReasonCategoriesResult">
      <Column Name="RejectReasonsCategory" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryDescription" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setUpdateRejectReason]" Method="_setUpdateRejectReason">
    <Parameter Name="RejectCode" Parameter="rejectCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ReasonName" Parameter="reasonName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="RejectRCategory" Parameter="rejectRCategory" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setDeleteRejectReason]" Method="_setDeleteRejectReason">
    <Parameter Name="RejectCode" Parameter="rejectCode" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getTemplateSupportDoc_List]" Method="_getTemplateSupportDoc_List">
    <Parameter Name="IsActive" Parameter="isActive" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="TemplateID" Parameter="templateID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getTemplateSupportDoc_ListResult">
      <Column Name="SupportingDocumentId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SupportingDocumentName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TemplateId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsMandatory" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TemplateSupportingDocument" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setTemplateSupportingDocument]" Method="_setTemplateSupportingDocument">
    <Parameter Name="SupportingDocumentId" Parameter="supportingDocumentId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="TemplateId" Parameter="templateId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="IsMandatory" Parameter="isMandatory" Type="System.String" DbType="VarChar(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_CheckTemplateSupportDoc]" Method="_CheckTemplateSupportDoc">
    <Parameter Name="SupportingDocid" Parameter="supportingDocid" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="TemplateId" Parameter="templateId" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_CheckTemplateSupportDocResult">
      <Column Name="Count_" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setUpdateTemplateSupportDoc]" Method="_setUpdateTemplateSupportDoc">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="TemplateId" Parameter="templateId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SupportDocId" Parameter="supportDocId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="IsMandatory" Parameter="isMandatory" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="ModifiedBy" Parameter="modifiedBy" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setDeleteTemplateSupportDoc]" Method="_setDeleteTemplateSupportDoc">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getSignatoryUsers]" Method="_getSignatoryUsers">
    <Parameter Name="UserGroup" Parameter="userGroup" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getSignatoryUsersResult">
      <Column Name="UserID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PersonName" Type="System.String" DbType="VarChar(188) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getUserSignatureDetails]" Method="_getUserSignatureDetails">
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getUserSignatureDetailsResult">
      <Column Name="UserID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PFXpath" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="SignatureIMGPath" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setUpdateUserSignatureDetails]" Method="_setUpdateUserSignatureDetails">
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PFXpath" Parameter="pFXpath" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="SignatureIMGPath" Parameter="signatureIMGPath" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setSignatorySignatureDetails]" Method="_setSignatorySignatureDetails">
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PFXpath" Parameter="pFXpath" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="SignatureIMGPath" Parameter="signatureIMGPath" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getAllExportSector]" Method="_getAllExportSector">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="_getAllExportSectorResult">
      <Column Name="ExportSector" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ExportId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setParentChildCustomerRequest]" Method="_setParentChildCustomerRequest">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="Address1" Parameter="address1" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address2" Parameter="address2" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address3" Parameter="address3" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="isSVat" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ContactPersonName" Parameter="contactPersonName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="ContactPersonDesignation" Parameter="contactPersonDesignation" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ContactPersonDirectPhoneNumber" Parameter="contactPersonDirectPhoneNumber" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ContactPersonMobile" Parameter="contactPersonMobile" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ContactPersonEmail" Parameter="contactPersonEmail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NCEMember" Parameter="nCEMember" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ParentCustomerId" Parameter="parentCustomerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ProductDetails" Parameter="productDetails" Type="System.String" DbType="Text" />
    <Parameter Name="ExportSector" Parameter="exportSector" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getClientCustomerRequestDetails]" Method="_getClientCustomerRequestDetails">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getClientCustomerRequestDetailsResult">
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SVat" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ContactPersonDesignation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactPersonDirectPhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonMobile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NCEMember" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TemplateId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TemplateName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Productdetails" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ExportSector" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExportSectorName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ParentCustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setApproveChildCustomer]" Method="_setApproveChildCustomer">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ParentCustomerID" Parameter="parentCustomerID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ChildCustomeID" Parameter="childCustomeID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="Address1" Parameter="address1" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address2" Parameter="address2" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Address3" Parameter="address3" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="isSVat" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ContactPersonName" Parameter="contactPersonName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="ContactPersonDesignation" Parameter="contactPersonDesignation" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ContactPersonDirectPhoneNumber" Parameter="contactPersonDirectPhoneNumber" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ContactPersonMobile" Parameter="contactPersonMobile" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ContactPersonEmail" Parameter="contactPersonEmail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NCEMember" Parameter="nCEMember" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ProductDetails" Parameter="productDetails" Type="System.String" DbType="Text" />
    <Parameter Name="ExportSector" Parameter="exportSector" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="TemplateId" Parameter="templateId" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getSupportingDOCforRequest]" Method="_getSupportingDOCforRequest">
    <Parameter Name="CustomerClientId" Parameter="customerClientId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="TemplateID" Parameter="templateID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getSupportingDOCforRequestResult">
      <Column Name="SupportingDocumentId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SupportingDocumentName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TemplateId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsMandatory" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getCustomerConsigneesReff" Method="getCustomerConsigneesReff">
    <Parameter Name="ParentCustomerID" Parameter="parentCustomerID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="getCustomerConsigneesReffResult">
      <Column Name="Consignee" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SeqNo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TemplateName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getCustomerClientList" Method="getCustomerClientList">
    <Parameter Name="ParentCustomerID" Parameter="parentCustomerID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="getCustomerClientListResult">
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ParentCustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setCertifcateRequestHeader]" Method="_setCertifcateRequestHeader">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="TemplateId" Parameter="templateId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="Consignor" Parameter="consignor" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Consignee" Parameter="consignee" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="InvoiceNo" Parameter="invoiceNo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="InvoiceDate" Parameter="invoiceDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="CountryCode" Parameter="countryCode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LoadingPort" Parameter="loadingPort" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PortOfDischarge" Parameter="portOfDischarge" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Vessel" Parameter="vessel" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PlaceOfDelivery" Parameter="placeOfDelivery" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TotalInvoiceValue" Parameter="totalInvoiceValue" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TotalQuantity" Parameter="totalQuantity" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="OtherComments" Parameter="otherComments" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="OtherDetails" Parameter="otherDetails" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="SealRequired" Parameter="sealRequired" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setCertificateRequestDetails]" Method="_setCertificateRequestDetails">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="GoodItem" Parameter="goodItem" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="ShippingMark" Parameter="shippingMark" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="PackageType" Parameter="packageType" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="SummaryDesc" Parameter="summaryDesc" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="HSCode" Parameter="hSCode" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setReffrennceRequest]" Method="_setReffrennceRequest">
    <Parameter Name="Consignee" Parameter="consignee" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ParentId" Parameter="parentId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="TemplateName" Parameter="templateName" Type="System.String" DbType="VarChar(150)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setSupportingDocUpload]" Method="_setSupportingDocUpload">
    <Parameter Name="RequestRefNo" Parameter="requestRefNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="DocumentId" Parameter="documentId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Remarks" Parameter="remarks" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="UploadedBy" Parameter="uploadedBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="UploadPath" Parameter="uploadPath" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="DocumentName" Parameter="documentName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="SignatureRequired" Parameter="signatureRequired" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getSavedCertificateRequest]" Method="_getSavedCertificateRequest">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getSavedCertificateRequestResult">
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Consignor" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Consignee" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="InvoiceNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LoadingPort" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PortOfDischarge" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Vessel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PlaceOfDelivery" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TotalInvoiceValue" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TotalQuantity" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OtherComments" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="OtherDetails" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ReasonCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SealRequired" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="GoodItem" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ShippingMark" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PackageType" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SummaryDesc" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="HSCode" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setWebBasedCertificateCreation]" Method="_setWebBasedCertificateCreation">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CertificatePath" Parameter="certificatePath" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="CertificateName" Parameter="certificateName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getClientTemplateNName" Method="getClientTemplateNName">
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ParentId" Parameter="parentId" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="getClientTemplateNNameResult">
      <Column Name="TemplateId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(618) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPersonName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ContactPersonDesignation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactPersonDirectPhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactPersonMobile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setCertificateApproval]" Method="_setCertificateApproval">
    <Parameter Name="CertificateId" Parameter="certificateId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ExpiryDate" Parameter="expiryDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="IsDownloaded" Parameter="isDownloaded" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="CertificatePath" Parameter="certificatePath" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="CertificateName" Parameter="certificateName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="IsValid" Parameter="isValid" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setCertificateReject]" Method="_setCertificateReject">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RejectBy" Parameter="rejectBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ResonCode" Parameter="resonCode" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setRejectUBCertificate]" Method="_setRejectUBCertificate">
    <Parameter Name="ModifiedBy" Parameter="modifiedBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RejectReasonCode" Parameter="rejectReasonCode" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setUploadBasedCRequests]" Method="_setUploadBasedCRequests">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="UploadPath" Parameter="uploadPath" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="InvoiceNo" Parameter="invoiceNo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SealRequired" Parameter="sealRequired" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setSupportingDocApproveRequest]" Method="_setSupportingDocApproveRequest">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SupportingDocID" Parameter="supportingDocID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RequestBy" Parameter="requestBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="UploadPath" Parameter="uploadPath" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="UploadDocName" Parameter="uploadDocName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getAllPendingCertificateRequests" Method="getAllPendingCertificateRequests">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="getAllPendingCertificateRequestsResult">
      <Column Name="CertificateType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CType" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CertificatePath" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="CertificateName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPersonEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SealRequired" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="CollectionType" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Createdby" Type="System.String" DbType="VarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="SummaryDesc" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ParentCustomer" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setUpdateUploadBCertifcateRequest]" Method="_setUpdateUploadBCertifcateRequest">
    <Parameter Name="ModifiedBy" Parameter="modifiedBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CertificateId" Parameter="certificateId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setSupportingDocApproveFrmCRquest]" Method="_setSupportingDocApproveFrmCRquest">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SupportingDocID" Parameter="supportingDocID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RequestBy" Parameter="requestBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="UploadPath" Parameter="uploadPath" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="UploadDocName" Parameter="uploadDocName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ApprovedBy" Parameter="approvedBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RequestDate" Parameter="requestDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DownloadPath" Parameter="downloadPath" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="DocExpireDate" Parameter="docExpireDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="CertificateRequestId" Parameter="certificateRequestId" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setUpdateSupportingDocUpload]" Method="_setUpdateSupportingDocUpload">
    <Parameter Name="UploadSeqNo" Parameter="uploadSeqNo" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="UploadedPath" Parameter="uploadedPath" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="DocumentName" Parameter="documentName" Type="System.String" DbType="VarChar(150)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getCRequestSupportingDOC]" Method="_getCRequestSupportingDOC">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getCRequestSupportingDOCResult">
      <Column Name="RequestRefNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SupportingDocumentId" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="SupportingDocumentName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="UploadedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UploadedBy" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UploadedPath" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="UploadSeqNo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DocumentName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SignatureRequired" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getUploadBCrequest]" Method="_getUploadBCrequest">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getUploadBCrequestResult">
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="InvoiceNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CertificatePath" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UploadPath" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SealRequired" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getPendingSDocApprovals]" Method="_getPendingSDocApprovals">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getPendingSDocApprovalsResult">
      <Column Name="RequestID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SupportingDocID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SupportingDocumentName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="UploadPath" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="UploadDocName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setUpdateSDApproveReq]" Method="_setUpdateSDApproveReq">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ApprovedBy" Parameter="approvedBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="DownloadPath" Parameter="downloadPath" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="DownloadDocName" Parameter="downloadDocName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DocExpireDate" Parameter="docExpireDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getPendingSDoc_byID]" Method="_getPendingSDoc_byID">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getPendingSDoc_byIDResult">
      <Column Name="RequestID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SupportingDocID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SupportingDocumentName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="UploadPath" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="UploadDocName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setRejectSDocumentRequest]" Method="_setRejectSDocumentRequest">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ApprovedBy" Parameter="approvedBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RejectReasonCode" Parameter="rejectReasonCode" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setRejectSupportDoc]" Method="_setRejectSupportDoc">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ApprovedBy" Parameter="approvedBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RejectReasonCode" Parameter="rejectReasonCode" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getDownloadCertificate]" Method="_getDownloadCertificate">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CertificateId" Parameter="certificateId" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="sealrequired" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="InvoiceNo" Parameter="invoiceNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ParentId" Parameter="parentId" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getDownloadCertificateResult">
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CertificateId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CertificateName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CertificatePath" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsValid" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="IsDownloaded" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SealRequired" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="PersonName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Designation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Consignor" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Consignee" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="created" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ctype" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getSignedCertificateSupportDoc]" Method="_getSignedCertificateSupportDoc">
    <Parameter Name="Certid" Parameter="certid" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getSignedCertificateSupportDocResult">
      <Column Name="RequestRefNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DPath" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Dname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DId" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="IsSigned" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getDownloadCertificateByID]" Method="_getDownloadCertificateByID">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getDownloadCertificateByIDResult">
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CertificateId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CertificateName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CertificatePath" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="InvoiceNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getSignedCertificateSupportDocForDownLoad]" Method="_getSignedCertificateSupportDocForDownLoad">
    <Parameter Name="Certid" Parameter="certid" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getSignedCertificateSupportDocForDownLoadResult">
      <Column Name="RequestRefNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DPath" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Dname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsSigned" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getSupportingDocumentDownload]" Method="_getSupportingDocumentDownload">
    <Parameter Name="ParentCustomer" Parameter="parentCustomer" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getSupportingDocumentDownloadResult">
      <Column Name="SupportingDocumentName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SupportingDocID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RequestID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DownloadPath" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="RequestBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CertificateRequestId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ApprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsDownloaded" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Consignor" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Consignee" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="InvoiceNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CertificateId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getSupportDocDownloadData]" Method="_getSupportDocDownloadData">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getSupportDocDownloadDataResult">
      <Column Name="RequestID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DownloadPath" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DownloadDocName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setDocumentCancelation]" Method="_setDocumentCancelation">
    <Parameter Name="DocID" Parameter="docID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Remark" Parameter="remark" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="CancelBy" Parameter="cancelBy" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="DocType" Parameter="docType" Type="System.String" DbType="VarChar(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getSupportingDocUsingCertificateId]" Method="_getSupportingDocUsingCertificateId">
    <Parameter Name="CertificateId" Parameter="certificateId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="invoiceSupDocID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getSupportingDocUsingCertificateIdResult">
      <Column Name="RequestID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DocType" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getAllCertificateCancelDetails]" Method="_getAllCertificateCancelDetails">
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="startdate" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="enddate" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="invoiceSupDoc" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="refNo" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getAllCertificateCancelDetailsResult">
      <Column Name="Ref_" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Approve_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="docTypes" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="Invoice" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Parent" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Approved_by" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Path_" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsDownloaded" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Req_id" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getAllParentCustomers]" Method="_getAllParentCustomers">
    <ElementType Name="_getAllParentCustomersResult">
      <Column Name="ParentCustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getCustomerRateDetails]" Method="_getCustomerRateDetails">
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="status" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="_getCustomerRateDetailsResult">
      <Column Name="RateId" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="RateName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Rates" Type="System.Decimal" DbType="Decimal(18,6) NOT NULL" CanBeNull="false" />
      <Column Name="PaidType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_ModifyCustomerRate]" Method="_ModifyCustomerRate">
    <Parameter Name="customerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RateId" Parameter="rateId" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Rate" Parameter="rate" Type="System.Decimal" DbType="Decimal(18,6)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getChildDeafaultRates]" Method="_getChildDeafaultRates">
    <Parameter Name="Cid" Parameter="cid" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getChildDeafaultRatesResult">
      <Column Name="RateId" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="RateName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RateValue" Type="System.Decimal" DbType="Decimal(2,2) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setChildNewRates]" Method="_setChildNewRates">
    <Parameter Name="Cid" Parameter="cid" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RatesId" Parameter="ratesId" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Value" Parameter="value" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getCanceleCertificate]" Method="_getCanceleCertificate">
    <Parameter Name="startDate" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="enddate" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="refNo" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getCanceleCertificateResult">
      <Column Name="DocumentId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CancelBy" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CancelDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DocumentType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Parent" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getCertificateRequestStatus]" Method="_getCertificateRequestStatus">
    <Parameter Name="RequestId" Parameter="requestId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="StartDate" Parameter="startDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="type" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="InvoiceNo" Parameter="invoiceNo" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getCertificateRequestStatusResult">
      <Column Name="Method" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RejectReasonCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="InvoiceNo" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Parent" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getCertificateStatus]" Method="_getCertificateStatus">
    <Parameter Name="CertificateNo" Parameter="certificateNo" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getCertificateStatusResult">
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Consignee" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="InvoiceNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TotalInvoiceValue" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getBackendSystemUsers]" Method="_getBackendSystemUsers">
    <ElementType Name="_getBackendSystemUsersResult">
      <Column Name="UserID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UserGroupID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PersonName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Designation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getUserGroups]" Method="_getUserGroups">
    <ElementType Name="_getUserGroupsResult">
      <Column Name="GroupId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setNewUser]" Method="_setNewUser">
    <Parameter Name="UserId" Parameter="userId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Groupid" Parameter="groupid" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PersonName" Parameter="personName" Type="System.String" DbType="VarChar(149)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Designation" Parameter="designation" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Createdby" Parameter="createdby" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_setEditUser]" Method="_setEditUser">
    <Parameter Name="UserId" Parameter="userId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Groupid" Parameter="groupid" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PersonName" Parameter="personName" Type="System.String" DbType="VarChar(149)" />
    <Parameter Name="Designation" Parameter="designation" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Createdby" Parameter="createdby" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="isactive" Type="System.String" DbType="VarChar(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getUserInfo]" Method="_getUserInfo">
    <Parameter Name="Userid" Parameter="userid" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getUserInfoResult">
      <Column Name="UserID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UserGroupID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PersonName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Designation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setResetPassword]" Method="_setResetPassword">
    <Parameter Name="UserId" Parameter="userId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Passwrod" Parameter="passwrod" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[_getAllParentCustomersDetails]" Method="_getAllParentCustomersDetails">
    <ElementType Name="_getAllParentCustomersDetailsResult">
      <Column Name="ParentCustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsSVat" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPersonName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ContactPersonDesignation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactPersonDirectPhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonMobile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NCEMember" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PaidType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getParentsChildrenDetails]" Method="_getParentsChildrenDetails">
    <Parameter Name="ParentId" Parameter="parentId" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getParentsChildrenDetailsResult">
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsSVat" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPersonName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ContactPersonDesignation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactPersonDirectPhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonMobile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContactPersonEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProductDetails" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ExportSector" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NCEMember" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PaidType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ParentCustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="RequestId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TemplateId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TemplateName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getAllInvoice]" Method="_getAllInvoice">
    <Parameter Name="startdate" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="enddate" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="ParentId" Parameter="parentId" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getAllInvoiceResult">
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_getSuppotingDocumentPeriodicDetail]" Method="_getSuppotingDocumentPeriodicDetail">
    <Parameter Name="customerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="status" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="startDate" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="endDate" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="InvoiceRateId" Parameter="invoiceRateId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="OtherRateId" Parameter="otherRateId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="supdocInvoiceRateId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="supdocOtherRateId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="AtachSheetId" Parameter="atachSheetId" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="_getSuppotingDocumentPeriodicDetailResult">
      <Column Name="RequestID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UploadDocName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SupportingDocID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Rates" Type="System.Decimal" DbType="Decimal(18,6) NOT NULL" CanBeNull="false" />
      <Column Name="RatesId" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[_setInvoiceRate]" Method="_setInvoiceRate">
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="InvoiceNo" Parameter="invoiceNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SuportingDocName" Parameter="suportingDocName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RateId" Parameter="rateId" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="RateValue" Parameter="rateValue" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
</Database>